#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --mem=32gb # Job memory request
#SBATCH --time=120:00:00 # Time limit hrs:min:sec
#SBATCH --partition=gpu
#SBATCH --nodelist=gpusrv-5
#SBATCH --gres=gpu:a6000:1

pwd; hostname; date; lscpu; nvidia-smi; nvidia-smi -L
echo "--- exec ---"
srun singularity exec --nv /opt/apps/containers/pygeo-torch113-py3.sif $1
echo "--- done ---"
date