[training]
domain_pddl = "benchmarks/ipc23-learning/satellite/domain.pddl"
tasks_dir = "benchmarks/ipc23-learning/satellite/training/easy"
plans_dir = "benchmarks/ipc23-learning/satellite/training_plans"
