name: Profile on IPC23LT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install build dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build and install
        run: |
          mkdir _wlplan
          python -m pip install -v .

      - name: Install test dependencies
        run: python -m pip install -r tests/test-requirements.txt

      - name: Profile
        run: pytest **/*profile*
