;; blocks=8, out_folder=training/easy, instance_id=27, seed=54

(define (problem blocksworld-27)
 (:domain blocksworld)
 (:objects b1 b2 b3 b4 b5 b6 b7 b8 - object)
 (:init 
    (arm-empty)
    (clear b1)
    (on b1 b6)
    (on b6 b2)
    (on b2 b7)
    (on b7 b8)
    (on b8 b5)
    (on b5 b4)
    (on b4 b3)
    (on-table b3))
 (:goal  (and 
    (clear b6)
    (on b6 b2)
    (on b2 b3)
    (on b3 b8)
    (on b8 b7)
    (on b7 b5)
    (on b5 b4)
    (on b4 b1)
    (on-table b1))))
