#!/bin/bash
#SBATCH --mail-type=END,FAIL # Mail events
#SBATCH --mail-user=dillon.chen1@gmail.com # Where to send mail
#SBATCH --mem=64gb # Job memory request
#SBATCH --time=120:00:00 # Time limit hrs:min:sec
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --nodelist=gpusrv-3

pwd; hostname; date; nvidia-smi; nvidia-smi -L
rm -rf builds/
singularity exec ../goose.sif python3 build.py
