#!/bin/bash
#SBATCH --ntasks=1 # Run on a single CPU
#SBATCH --mem=64gb # Job memory request
#SBATCH --time=120:00:00 # Time limit hrs:min:sec

pwd; hostname; date; grep MemTotal /proc/meminfo; 
echo "--- exec ---"
srun singularity exec ../gpu.sif $1
echo "--- done ---"
date
