name: Apptainer

on:
  push:
    branches:
      - main

jobs:
  build:

    if: github.repository == 'DillonZChen/goose'
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Install submodules
        run: |
          git submodule update --init --recursive

      - name: Build image
        run: |
          python3 apptainer/build.py

      - name: Login and deploy image
        if: (github.event_name != 'pull_request')
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u ${GITHUB_ACTOR} --password-stdin oras://ghcr.io

          # We cannot use ${GITHUB_REPOSITORY} as the below command requires lowercase.
          # See https://github.com/apptainer/apptainer/issues/2272
          apptainer push goose.sif oras://ghcr.io/dillonzchen/goose:latest

          # Image can now be pulled with "apptainer pull oras://ghcr.io/dillonzchen/goose:latest"
