name: Apptainer

# Run for all pushes to the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-image:
    name: Build Apptainer image
    if: github.repository == 'DillonZChen/goose'
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Install wlplan submodule
        run: |
          git submodule update --init --recursive wlplan

      - name: Build image
        run: |
          apptainer build Goose.sif Goose.def

      - name: Login and deploy image
        if: (github.event_name != 'pull_request')
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login -u ${GITHUB_ACTOR} --password-stdin oras://ghcr.io
          apptainer push Goose.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
          # Image can now be pulled with "apptainer pull oras://ghcr.io/${GITHUB_REPOSITORY}:latest"
